### PR TITLE
LPD-45162 Remove "Remove Membership" shows confirmation alert window

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-41844

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Review by jonathanmccann — APPROVED** [review]

**Comment by MrJohn1911** [comment]
ci:report:100187525

**Comment by MrJohn1911** [comment]
ci:report:100187525

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
