### PR TITLE
LPD-29294, LPD-29407 Add option to show the popover warning after hiding it

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/154424

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:reevaluate:1407401_11101

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
Failures are not related, https://testray.liferay.com/#/project/35392/routines/45357/build/20193095

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
