### PR TITLE
LPD-29089 Changes are filtered by asset link type and group

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-29089

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
Failures unrelated

**Comment by brookedalton** [comment]
Hi @pei-jung @david-truong, is this ok to be forwarded? The publication failures are unrelated and I tried to address ~40 of the failures in [LPD-37022](https://liferay.atlassian.net/browse/LPD-37022)

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
