### PR TITLE
LPD-40431 Breadrcumb Horizontal ADT is missing accessibility attribute "aria-current"

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40431

# How am I fixing it?

The template has been updated to include the required aria-current attribute. This is only applied to the currently selected item.

# How can you verify that it works?

In `modules/test/playwright` run `npm run playwright -- test -g 'LPD-40431'`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
