### PR TITLE
LPD-36275 Searchbar in membership requests view is not working

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36275

# How am I fixing it?

The search bar's keywords are currently not used in any search query. Since the `MembershipRequest` table currently does not have relevant information to search it was decided to remove the search bar.

# How can you verify that it works?

In `modules/test/playwright` run `npm run playwright -- test -g 'LPD-36275'`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:49436136

**Comment by david-truong** [comment]
@jonathanmccann is the unique failure related?

**Comment by jonathanmccann** [comment]
@david-truong I don't think so, these changes don't affect Navigation Menus.

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
