### PR TITLE
LPD-44049 Update path in order to find drag handler for page to be moved

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44049

# How am I fixing it?

The path needs to be updated in order to find the drag handler.

# How can you verify that it works?

In the root folder run `ant -f build-test.xml run-selenium-test -Dtest.class=NavigationMenuWidget#ConfigureDisplayTemplateOfNavigationMenuWidget`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@liferay-page-management Since the change is in `PagesAdmin` I wanted to make you aware. If there are concerns please let me know.

**Comment by david-truong** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
