### PR TITLE
LPD-43196 Redirect URLs doesn't handle property locale.prepend.friendly.url.style when it's value is set to 3

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-43196

Steps to reproduce are in the Ticket.

To test if it works, just follow the steps or run in `<portal-home>/modules/apps/friendly-url/friendly-url-test/`:

 `gw testIntegration --tests FriendlyURLServletLocalizedFriendlyURLTest.testIncludeI18nPathCustomLocaleAlgorithm3`
 `gw testIntegration --tests FriendlyURLServletLocalizedFriendlyURLTest.testIncludeI18nPathDefaultLocaleAlgorithm3`

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
@MrJohn1911 `testIncludeI18nPathDefaultLocaleAlgorithm3` isn't passing locally for me. I think the final parameter `boolean includeI18nPath` for the call to `_assertLocalizedSiteLayoutFriendlyURL` should be set to `false`?

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:stop

**Pull request closed without merging**
