### PR TITLE
LPD-44829 Remove info panel from User and Organization tabs

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-44829

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
Pending the changes as we discussed.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
> @MrJohn1911 this seems uglier why are we making this change?

Hi @david-truong 

The main reason for this pull is to remove the info panel from users and organizations tabs, but @jonathanmccann requested to remove this code in `users.jsp` and `organizations.jsp`, so it looks like `user_groups.jsp`:

```
<div class="closed sidenav-container sidenav-right" id="<portlet:namespace />infoPanelId">
	<div class="sidenav-content">
		<clay:container-fluid>
```

So I sent the pr just to make sure this change is expected or not.

**Comment by jonathanmccann** [comment]
Sorry about that. Looks like those divs were applying some CSS. Can you add `container-fluid container-fluid-max-xl` to

https://github.com/liferay-site-management/liferay-portal/pull/1641/commits/e9e14693ae93e8e171e8c09e935d010947743059#diff-1820dac724670cfcb4c38e3048b265555ef3ca1caf4d106cfb3c7f5e8a8fed3dR28

https://github.com/liferay-site-management/liferay-portal/pull/1641/commits/e9e14693ae93e8e171e8c09e935d010947743059#diff-ff39dab717f8dd36ef33e1192c47f68e6a91feeab4098a225a9cbc7501eaf3c4R36

This matches the CSS for the User Group tab

https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-memberships-web/src/main/resources/META-INF/resources/user_groups.jsp#L32

It made the UI look the same in my testing but let me know if something still seems off.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:report:95808693

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:95881011

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:report:96659082

**Comment by MrJohn1911** [comment]
ci:forward

**Pull request closed without merging**
