### PR TITLE
LPD-29089 Changes are filtered by asset link type and group

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-29089

### CODE REVIEW

**Comment by brookedalton** [comment]
Changes requested: https://github.com/brianchandotcom/liferay-portal/pull/154525#issuecomment-2372547585

**Comment by brookedalton** [comment]
Hey @ctang3, can you please review the var names in ViewChangesDisplayContext?

**Comment by david-truong** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by ctang3** [comment]
@brookedalton The names in ViewChangesDisplayContext look good to me!

**Review by ctang3 — APPROVED** [review]

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
