### PR TITLE
LPS-158789 allow you to change publication via URL parameter

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@xbrianlee @suilin can one of you help me add some tests?

1. Enable publications
2. Create a publication
3. Make changes to a page
4. View page in production
5. Add `previewCTCollectionId=1` or whatever the collectionId happens to be
6. It should render the page with your new changes in preview mode.

Additionally... if you set it to a collectionId that does not exist/do not have access to/or not in draft mode... it should display an error.

**Comment by suilin** [comment]
Hi @david-truong, I'm adding the tests, but I have some questions when testing it
* When I navigate to `http://localhost:8080/web/guest?previewCTCollectionId=1` with the steps you provided, nothing happens, it's still in production mode instead of in the preview mode.
* Same results when set it to a collectionId that does not exist/do not have access to/or not in draft mode, what the error should display? Thanks.

**Comment by suilin** [comment]
ci:test:bundle

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
resent to https://github.com/liferay-publications/liferay-portal/pull/161 with funcational tests.

**Pull request closed without merging**
