### PR TITLE
LPD-42463 Bookmarks dependency is not being resolved in SiteInitializer module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-42463

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:report:72050813

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
