### PR TITLE
LPD-43884 Fix MissingTableReferenceDefinitionTest failure

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-43884

### CODE REVIEW

**Comment by david-truong** [comment]
@ctang3 there are no relationships in these tables?

**Comment by ctang3** [comment]
@david-truong I can add them. I added the TableReferenceDefinitions to fix the tests but wasn't sure if Commerce should then define the relationships.

**Comment by david-truong** [comment]
i don't think any team has ever done that for us before

**Comment by ctang3** [comment]
There are a some that were implemented by Andrea Sbarra in this module (commerce-product-service), surprisingly

**Comment by david-truong** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:sf

**Comment by ctang3** [comment]
Closing this to resend just the unimplemented TableReferenceDefinitions with the implementation and tests to be sent in a separate subtask, as discussed in our meeting this morning: https://github.com/liferay-site-management/liferay-portal/pull/1634

**Pull request closed without merging**
