### PR TITLE
LPD-33582 Add buttons to popover that warn users when changing between contexts

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-33582](https://liferay.atlassian.net/browse/LPD-33582)

image

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@gislayne-vitorino are we adding the ability to no longer receive the reminder in a different ticket?

**Comment by gislayne-vitorino** [comment]
@david-truong Yes, in this ticket: https://liferay.atlassian.net/browse/LPD-29584

**Comment by gislayne-vitorino** [comment]
The failure is related, but it's passing on my local, I'm investigating to see what could be

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
The failure is not related

**Comment by pei-jung** [comment]
@gislayne-vitorino the popover should not appear after the user choses to stay in the current publication or switch to a different publication.

**Comment by gislayne-vitorino** [comment]
@pei-jung I thought the popover should keep appearing until we add the option to silence it. I'm going to modify the code and test

**Comment by gislayne-vitorino** [comment]
Thinking now, shouldn't it be that when they click in any of the buttons then the popover would not appear unless the site changes again? Because right now the popover does not appear in production, but if they click on it, then go back to the publication again, the popover still appears.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
