### PR TITLE
LPD-43724 Get the workflow task from production when the publication has been published

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPD-43724

Notifications for published publication were being deleted because we were attempting to get the workflow task using the ctCollectionId. But after publishing the publication, the workflow task is not under production.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@noornajj please look at the failure

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
Tha playwright test passed locally for me.

**Comment by noornajj** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
