### PR TITLE
LPD-34807 Remove CT_ALL mode

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
Hey @david-truong do you mind taking a quick look at this to make sure I don't miss anything? Thanks!

**Comment by pei-jung** [comment]
ci:report:79319017

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@pei-jung this looks good from my side

**Comment by pei-jung** [comment]
ci:report:79319349

**Comment by pei-jung** [comment]
ci:report:79319017

**Comment by pei-jung** [comment]
ci:report:79319349

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
