### PR TITLE
LPD-38654 Publication bar disappears after clicking on published timeline icon

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: https://liferay.atlassian.net/browse/LPD-38654

Problem: the publication bar would disappear after clicking on the timeline icon when viewing a document library and the ff was disabled

After fixing it I discovered that the deleteURL was broken, and after that the editURL was broken as well, so this PR aims to fix these issues.

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
The tests `PublicationsUpgrade#AssertPublicationsHistoryRemainsAfterUpgradingArchive7413u73` and 
` PublicationsDM#CanViewDocumentFolderAndFileOverMultiplePublications` passed, but as the playwright tests failed to build I will run the publications suite again just to be sure

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
Failures are not related

**Review by ctang3 — APPROVED** [review]

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
