### PR TITLE
LPD-34172 Portlets preview falling when friendlyURL ends with a slash

### PR DESCRIPTION
**Pull request by MrJohn1911**
previous pull: https://github.com/brianchandotcom/liferay-portal/pull/154155

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:upgrade

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
