### PR TITLE
LPD-38030 Landing page doesn´t work with special characters in the URL

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38030

# How am I fixing it?

Prior to sending the redirect the URL is now normalized with encoding, much like how the friendly URL is saved to the database.

# How can you verify that it works?

In `portal-events-test` run `gw testIntegration --tests *.DefaultLandingPageActionTest`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:report:48299897

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
