### PR TITLE
LPD-37511 Remove feature flag for LPD-10800

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-37511

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
SF failure looks related to https://liferay.slack.com/archives/C19PWQ74J/p1727389092914749

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Resent due to rebase error: https://github.com/liferay-site-management/liferay-portal/pull/1436

**Pull request closed without merging**
