### PR TITLE
LPD-42499 Technical Task | Replace text for Page Conflict message on Check Conflict screen

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: https://liferay.atlassian.net/browse/LPD-42498

Currently this is how it looks 
image

the link was add through a learn resource, so it needs to be updated first and only then it will appear, for testing purposes here's the look of it with the other learn resource that was already available on our side 
image

After the new one is deployed it will be shown with the full sentence chosen

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
Failures are not related, the semantic versioning error is on ObjectDefinitionLocalServiceUtil

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
