### PR TITLE
LPD-39736 Increase timeout for stopped service to restart

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-39734

### CODE REVIEW

**Comment by brookedalton** [comment]
Tested 20 times in a row: https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/14224/jenkins-report.html

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
