### PR TITLE
LPD-41195 Update CODEOWNERS for Site Management

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @david-truong

### CODE REVIEW

**Comment by jonathanmccann** [comment]
I will take a closer look to see if any packages can be narrowed in scope.

**Comment by jonathanmccann** [comment]
Updated to be more specific in the cases of Site Initializer and Site. Let me know what you think @david-truong

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by david-truong** [comment]
@jonathanmccann there's a conflict

**Comment by jonathanmccann** [comment]
@david-truong Thank you, updated.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
