### PR TITLE
LPD-38791 - All "other" fields should be mergeable by default for all change tracked entities

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj after discussing with product we decided to go all out with setting as many fields as possible to merge.

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:help

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:help

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:49950034

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:report:54369476

**Comment by david-truong** [comment]
ci:test:stable

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Pull request closed without merging**
