### PR TITLE
LPD-38791 - All status related fields should be mergeable by default for all change tracked entities

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relelvant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:report:45271819

**Comment by david-truong** [comment]
@noornajj are the failures related?

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:48575853

**Comment by david-truong** [comment]
ci:report:48645321

**Pull request closed without merging**
