### PR TITLE
LPD-25688 Create a pop up screen to view the entire history of an entity

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-25688

image

Tests will be added in https://liferay.atlassian.net/browse/LPD-34627 since that will have the API changes for the modal's fields to be populated correctly.

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Review by pei-jung — CHANGES_REQUESTED** [review]
@ctang3 table styling is off. Please check the mockup carefully to make sure it matches the design. These are the ones I've noticed from your screenshot:
- [x] table rows should not have zebra-striping
- [x] table needs borders on all sides
- [x] no border for table columns
- [x] Name column should be renamed to **Publication**
- [x] Change column should be named **Changed**

Mockup
Screen Shot 2024-08-23 at 9 14 53 AM


We need frontend tests for this. Please add playwright tests to assert the View More button and modal. Also, these changes need to be added behind a feature flag as stated in https://liferay.atlassian.net/browse/LPD-20556.

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
@pei-jung Updated with your requested changes. I'm not sure what to do about the SF error. When I run source formatting on my local, I don't see any issues. Is this something you have seen before? The tsconfig.json was modified to add the `@liferay/frontend-data-set-web` library.

```
[exec]    · apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/tsconfig.json is outdated
```

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Pull request closed without merging**
