### PR TITLE
LPD-39408 Pagination on Custom Site Templates at Site creation refreshes the page

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39408

# How am I fixing it?

The tab the user is currently on is missing from the portlet URL. This adds the parameter so that they stay in the current tab when clicking on search results.

# How can you verify that it works?

In `modules/test/playwright` run `npm run playwright -- test -g 'LPD-39408'`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by MrJohn1911 — APPROVED** [review]

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
