### PR TITLE
LPD-39433 Enable for web structures and templates the publication timeline history

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
In progress, adding tests

This is an update for: [LPD-39433](https://liferay.atlassian.net/browse/LPD-39412)

The first commit relates to checking if the classPK is being passed or if it's null, some entities weren't responding well to the api with the `&classPK=0` at the end of the query, like ddmStructures and ddmTemplates.

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
Failures are not related

**Comment by gislayne-vitorino** [comment]
Failure is not related, the test with the unique failure found has been flaky

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
