### PR TITLE
Lpd 26155

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPD-26155

I still need to add the tests. But I thought we could start the review while I write the tests in case any adjustments need to be made.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
