### PR TITLE
LPD-35694 Technical Task | TestDiscardCTEntryLayout failing with InitializationException

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-35694](https://liferay.atlassian.net/browse/LPD-35694)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/153983#event-14169227425

I added the pop to testDiscardCTEntryLayout, but I'm not sure if I should add it as well for testCheckConflictsGroup, if so, should I add the pop twice?

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
>I added the pop to testDiscardCTEntryLayout, but I'm not sure if I should add it as well for testCheckConflictsGroup, if so, should I add the pop twice?
Yes, you need to pop for every push. Pop is always done in a try-finally block to ensure that it gets called even when exception occurs. For `testDiscardCTEntryLayout`, if you know which call requires the serviceContext, add the push directly in that try block. Otherwise, wrap it in another try-finally block.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@gislayne-vitorino do you know if these failures were caused by a different change?  Why did this test start failing all of a sudden.

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
The failure is not related

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
