### PR TITLE
LPD-38937 Use ConfigurationTestUtil to reduce flakiness and ensure the configuration has been updated before trying to retrieve it

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38937

# How am I fixing it?

The test's flakiness comes from the configuration not being updated in time for the retrieval call. Using the ConfigurationTestUtil now gives it time and emulates the logic in testGetFriendlyURLSeparatorsJSON.

# How can you verify that it works?

In `friendly-url-test` run `gw testIntegration --tests *.FriendlyURLSeparatorConfigurationManagerTest`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
