### PR TITLE
LPD-36356 Convert xml.sitemap.index.enabled portal property to configuration

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36356

# How am I fixing it?

These changes include removing the `xml.sitemap.index.enabled` property, adding a new configuration instead, and an upgrade process in case a client has previously set this property to `false`.

# How can you verify that it works?

In `site-test` run:
- `gw testIntegration --tests *.XMLSitemapIndexEnabledConfigurationUpgradeProcessTest`
- `gw testIntegration --tests *.SitemapManagerTest`
- `gw testIntegration --tests *.SaveCompanyConfigurationMVCActionCommandTest`

/cc @mrjohn1911

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@jonathanmccann this looks good to me

**Comment by jonathanmccann** [comment]
ci:test:upgrade

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:report:14879260

**Comment by jonathanmccann** [comment]
Resent to address test failures - https://github.com/liferay-site-management/liferay-portal/pull/1408

**Pull request closed without merging**
