### PR TITLE
LPS-177525 - Change workflow button from "submit-for-publication" to "submit-for-workflow"

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@noornajj @xbrianlee @suilin i have no idea if i did this correctly... but I did a mass search and replace to try and update all the tests

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:stop:relevant

**Comment by xbrianlee** [comment]
@david-truong These results look good! Nice job on the test fix 🥇

**Comment by xbrianlee** [comment]
ci:stop:relevant

**Comment by xbrianlee** [comment]
ci:stop:stable

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/131442

**Pull request closed without merging**
