### PR TITLE
LPD-34172

### PR DESCRIPTION
**Pull request by jonathanmccann**
Previously sent under https://github.com/liferay-site-management/liferay-portal/pull/1382

https://liferay.atlassian.net/browse/LPD-34172

/cc @mrjohn1911

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@adolfopa Would you mind looking over these changes as well since they touch your components? If you'd rather we can forward it on to you as well. Thanks!

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz @boton Can you take a look at this? It looks ok to me, but it may conflict with your changes for categories in friendly urls.

**Comment by robertoDiaz** [comment]
> @robertoDiaz @boton Can you take a look at this? It looks ok to me, but it may conflict with your changes for categories in friendly urls.

I think it should not since it's controling a case that never worked.

In any case categories in friendly urls feature has a ton of tests

**Comment by adolfopa** [comment]
@jonathanmccann This looks ok to us, so feel free to forward once it is ready.

**Comment by jonathanmccann** [comment]
ci:test:upgrade

**Comment by MrJohn1911** [comment]
ci:report:9604932

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
