### PR TITLE
LPD-43359 Menu items are shown for review changes with view permissions

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-43359

### CODE REVIEW

**Comment by brookedalton** [comment]
Screenshot 2024-12-02 at 2 00 55 PM

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Comment by brookedalton** [comment]
Failures related to https://liferay.slack.com/archives/C19PWQ74J/p1733247035502499?thread_ts=1733224766.797639&cid=C19PWQ74J

**Comment by noornajj** [comment]
Hi @brookedalton 
It looks like this issue also occurs for view only users https://liferay.atlassian.net/browse/LPD-38750
Can you change the logic to check whether the user has update permissions?

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
Resent with functional failure fix: https://github.com/liferay-site-management/liferay-portal/pull/1603

**Pull request closed without merging**
