### PR TITLE
LPD-44579 implement table reference definitions

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-44579

ListTypeDefinitionTableReferenceDefinition doesn't have a TableReferenceDefinitionTest because it is not a change tracked entity.

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:stop

**Comment by ctang3** [comment]
ci:stop

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
