### PR TITLE
LPD-42050 Duplicated groupKey when updating a non-group type group with different locale

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42050

# How am I fixing it?

Groups that aren't of the `group` type use their `classPK` as the `groupKey`. This update logic didn't take this into account. Now the `groupKey` is only updated if it is tied to the group's name.

# How can you verify that it works?

In `site-test` run `gw testIntegration --tests *.GroupServiceTest`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@jonathanmccann can you check the failures?

**Comment by jonathanmccann** [comment]
ci::report:68092721

**Comment by jonathanmccann** [comment]
ci:report:68092721

**Comment by jonathanmccann** [comment]
@david-truong The site-management ones are not related and the relevant don't appear to be related.

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
