### PR TITLE
LPD-34172 Portlets preview falling when friendlyURL ends with a slash

### PR DESCRIPTION
**Pull request by MrJohn1911**
### **What is this trying to solve?**

https://liferay.atlassian.net/browse/LPD-34172

### **How am I fixing it?**

I'm verifying if the FriendlyURL that is been added ends with a trailing slash, if so, the method that verifies it throws an Exception to the user. Also, I'm creating upgrade processes so if a client has any FriendlyURL that has a trailing slash in their database, they can be formatted to new FriendlyURLs without it.

### **How can you verify that it works?**

In friendly.url..test, run gw testIntegration --tests *.FriendlyURLEntryLocalServiceTest
In blogs.test, run gw testIntegration --tests *.BlogsFriendlyURLFormatUpgradeProcessTest
In journal.test, run gw testIntegration --tests *.JournalArticleFriendlyURLFormatUpgradeProcessTest

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:5785374

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:upgrade

**Comment by MrJohn1911** [comment]
ci:report:6936190

**Comment by jonathanmccann** [comment]
Please see https://github.com/liferay-site-management/liferay-portal/pull/1387

**Comment by jonathanmccann** [comment]
ci:close

**Pull request closed without merging**
