### PR TITLE
LPS-157581 Add test to configure change tracked entities to skip publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@suilin can you double check I fixed the conflict for Publications.testcase correctly

**Comment by suilin** [comment]
Hi @david-truong, I checked it manually and I found it doesn't work for the service and model, could you help to look at it?Thank you!
* I tried com.liferay.blogs.service.impl.BlogsEntryServiceImpl, 
* com.liferay.journal.service.impl.JournalArticleServiceImpl,
* com.liferay.portal.kernel.model.Group,
* com.liferay.portal.kernel.model.Role

**Comment by david-truong** [comment]
Hey @suilin ... right now you need to add both `com.liferay.portal.kernel.service.RoleService` and `com.liferay.portal.kernel.service.RoleLocalService`

The whole thing is pretty fragile though so I'm still thinking through how we can implement this safely

**Comment by suilin** [comment]
Hi @david-truong, it works for the services under kernel, but it doesn't work for the module one, I used com.liferay.journal.service.impl.JournalArticleServiceImpl
com.liferay.journal.service.impl.JournalArticleLocalServiceImpl, but it doesn't work, is it the expected result? Does _isProductionOnlyClassName only for kernel ones? Thank you!

**Comment by suilin** [comment]
@david-truong, another question, if we type `com.liferay.portal.kernel.service.RoleService` and `com.liferay.portal.kernel.service.RoleLocalService` into one textbox, it doesn't work, so that we need to seperate them into two textbox, is it expected? Thanks.

**Comment by suilin** [comment]
@david-truong, I have another question, if I type `com.liferay.portal.kernel.service.RoleService,com.liferay.portal.kernel.service.RoleLocalService` into one textbox, it doesn't work, so I need to seperate them into two textboxes, is it the expected result? thanks.

**Comment by david-truong** [comment]
yes it has to be two different text boxes... like i said I'm not too happy with the user experience right now..  Also for the modules service.. you need to use the LocalService/Service and not the Impl for now... can you try that?

**Comment by suilin** [comment]
@david-truong, I used the api instead of impl, it works, thanks for your help.

**Comment by suilin** [comment]
@david-truong, thanks for your help, I use the api instead of imp, now it works fine to add and edit but it doesn't work to delete and I uploaded the console long on [here](https://gist.github.com/suilin/05870a13f68d5970b24f075f230d029a), can you help to look at it? I'm updaing the tests, do I need to send liferay-publications firstly?

I used `com.liferay.journal.service.JournalArticleService` and `com.liferay.journal.service.JournalArticleLocalService`

**Comment by suilin** [comment]
I updated the test and sent to https://github.com/liferay-publications/liferay-portal/pull/176

**Pull request closed without merging**
