### PR TITLE
LPD-39428 Add support for Forms to have publication timeline history

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-39428

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Needs https://github.com/liferay-site-management/liferay-portal/pull/1501/commits/33dfbb8374f12326493a4eecd5041d0d2c5e02ea before testing/sending

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
