### PR TITLE
LPD-44372 Generate notification links for workflow tasks related to p…

### PR DESCRIPTION
**Pull request by noornajj**
https://liferay.atlassian.net/browse/LPD-44372

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
