### PR TITLE
LPD-34172 Portlets preview falling when friendlyURL ends with a slash

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:report:78552419

**Comment by jonathanmccann** [comment]
There are a couple of issues I found while testing this:

1. Other locales' friendly URLs are deleted from `FriendlyURLEntryLocalization` for Journal Articles
2. The `FriendlyURLEntry` loses its `classPK` for Journal Articles
3. URLs with multiple trailing slashes only have the final slash removed instead of all

What do you think about:

1. Remove `FriendlyURLFormatUpgradeProcess`
2. In the Blogs/Journal upgrade processes do the following
a. Query the `FriendlyURLEntryLocalization` table for URLs that end in a slash and have a class name ID associated with Blogs or Journal Articles (eg `SELECT DISTINCT classPK FROM FriendlyURLEntryLocalization WHERE urlTitle LIKE '%/' AND classNameId = 00000;`)
b. Collect all of the `classPK`s for those entries
c. For each `classPK` update the URLs in `FriendlyURLEntryLocalization`
d. Update the `BlogsEntry/JournalArticle` table with the associated URL for the correct locale (locale not necessary for Blogs since they are not localized)

This would all be done through raw SQL to avoid issues where the service depends on the upgrade but the upgrade depends on the service and it never runs (https://liferay.atlassian.net/wiki/spaces/ENGCOREUPGRADE/pages/1654719711/Upgrade+Development+Training#Golden-rule). Thanks @adolfopa for catching this.

Since it's done through SQL alone the issue with losing the `classPK` should be mitigated and updating the `FriendlyURLEntryLocalization` table directly will maintain the other translated URLs.

Also, is https://github.com/liferay-site-management/liferay-portal/pull/1366/commits/ab5dc2409ee83d3f95dee17b9c0933e5915a7b27 necessary? I thought it wasn't possible to add a Group friendly URL with a trailing slash?

Let me know what you think and if there's something I've overlooking or misunderstanding.

**Pull request closed without merging**
