### PR TITLE
LPS-179032 - As a publication admin, I would like to hide applications that shouldn't be used in a publication

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
@suilin can you check the results and forward if the results are okay?

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
