### PR TITLE
LPD-34884 Slow performance when viewing list of Sites while groups.complex.sql.class.names includes Group model

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-34884

# How am I fixing it?

This query serves to filter out groups based on a user's permissions. Previously, it was fetching all of the users and their roles for all groups. Later, when checking the permission, it then filtered based on the user's ID.

With this change it now filters based on the user's ID earlier so we are not fetching all users, thus increasing the performance.

# How can you verify that it works?

In `site-test` run `gw testIntegration --tests *.GroupFinderTest`

No new tests are being added because this is a performance fix and the logic is already being tested.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@david-truong If you wouldn't mind double checking the SQL query to make sure everything looks correct. It's very intricate so I would appreciate a second pair of eyes on it.

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:report:73862987

**Comment by david-truong** [comment]
ci:test:site-management

**Pull request closed without merging**
