### PR TITLE
LPD-37835 Technical Task | Flaky NullPointerException in PublicationUserNotificationHandlerTest

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPD-37835](https://liferay.atlassian.net/browse/LPD-37835)

The cause for the errors is the service that is stopped in `testGetBodyForStoppedService()`, it caused the service to not load in time for the rest of the tests that also used JournalArticle service.

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:publications

**Comment by gislayne-vitorino** [comment]
The failures are not related and PublicationUserNotificationHandlerTest passed as well

**Comment by ctang3** [comment]
Nice work @gislayne-vitorino!

**Review by ctang3 — APPROVED** [review]

**Comment by ctang3** [comment]
ci:forward

**Pull request closed without merging**
