### PR TITLE
LPD-37997 Site settings with repeated languages after changing Locale settings for instance

### PR DESCRIPTION
**Pull request by MrJohn1911**
From @jonathanmccann (https://github.com/liferay-site-management/liferay-portal/pull/1473)

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@MrJohn1911 Can you resolve the conflict and then execute the tests? Thanks!

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:46418335

**Comment by MrJohn1911** [comment]
@jonathanmccann the tests are ok!

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by MrJohn1911** [comment]
ci:forward

**Comment by MrJohn1911** [comment]
ci:forward:force

**Pull request closed without merging**
