### PR TITLE
LPD-44987 Set CTSQLMode to CT_ONLY if we are not in Production mode

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-44987

@david-truong I'm not sure if this is the best way to go about fixing this. Could you please take a look? I have more details in the ticket to provide context on this bug. Will add a test once I get confirmation. Thanks!

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@ctang3 this doesn't seem like the correct solution.  I don't see how modifying the get will change anything once you publish.

**Comment by ctang3** [comment]
@david-truong Ahh I see, you're right - after publishing it still shows the duplicate. I'll look into an alternate solution.

**Pull request closed without merging**
