### PR TITLE
LPD-40501 Focus on name input is lost when creating new site

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40501

# How am I fixing it?

The issue is resolved by hiding the input until everything has fully loaded. That way focus is not taken away from the field. This mimics the changes made in https://liferay.atlassian.net/browse/LPD-20368 for the same issue when creating Pages.

The delayed focus on the field is no longer necessary either and users can immediately be granted focus on the input field to begin typing.

# Why doesn't this include any test?

To reproduce this issue a slow network connection needs to be simulated. If the Javascript modules load quickly, as in a regular use case, this issue will not be reproduced.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
