### PR TITLE
LPD-37997 Site settings with repeated languages after changing Locale settings for instance

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @mrjohn1911 (https://github.com/liferay-site-management/liferay-portal/pull/1458)

> What is this trying to solve?
> 
> https://liferay.atlassian.net/browse/LPD-37997
> How am I fixing it?
> 
> This change is basically removing the logic for selecting the current locale in the Site Settings from DisplaySettingsDisplayContext since this logic is already present in the SiteLanguageConfiguration file.
> How can you verify that it works?
> 
> Reproduce the steps described in the ticket and verify that the issue is no longer reproducing or run the Check current site locales based on instance locales test in modules/test/playwright/tests/site-admin-web/siteInitializerSelection.spec.ts.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:44659540

**Comment by jonathanmccann** [comment]
ci:close

**Pull request closed without merging**
