### PR TITLE
LPD-44167 Technical Task | Resolve test failures in SitesUseCase#SitesDemoSiteManagement

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by MrJohn1911** [comment]
ci:report:90590451

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:site-management

**Comment by jonathanmccann** [comment]
ci:forward

**Pull request closed without merging**
