### PR TITLE
LPD-43624 rest builder updated

### PR DESCRIPTION
**Pull request by ctang3**
https://liferay.atlassian.net/browse/LPD-43624

### CODE REVIEW

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:sf

**Comment by david-truong** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:sf

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
@ctang3 the rest builder failure needs to be fixed

**Comment by ctang3** [comment]
ci:test:relevant

**Comment by ctang3** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:forward:force

**Comment by david-truong** [comment]
ci:test:relevant

**Pull request closed without merging**
