### PR TITLE
LPD-39630 Adjust test to check for 404 utility page instead of error …

### PR DESCRIPTION
**Pull request by noornajj**
…message

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:publications

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
I don't think relevant is pending or waiting for anything, this is ready to forward from the CI side I believe

**Comment by david-truong** [comment]
ci:forward

**Pull request closed without merging**
