### PR TITLE
LPD-34884 Slow performance when viewing list of Sites while groups.complex.sql.class.names includes Group model

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-34884

# How am I fixing it?

This query serves to filter out groups based on a user's permissions. Previously, it was fetching all of the users and their roles for all groups. Later, when checking the permission, it then filtered based on the user's ID.

With this change it now filters based on the user's ID earlier so we are not fetching all users, thus increasing the performance.

This differs from https://github.com/liferay-site-management/liferay-portal/pull/1354 in when the parameters are set. Now, it will work regardless of the parameter order.

# How can you verify that it works?

In `site-test` run `gw testIntegration --tests *.GroupFinderTest`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:report:82172451

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:forward:force

**Pull request closed without merging**
